default:
  app_url: https://shinypro.synapse.org/users/nkauer/stopadforms/

testing:
  app_url: https://shinypro.synapse.org/users/nkauer/stopadforms-test/
  
aws-testing:
  app_url: http://stopa-stopa-5uosybijubfh-4250912.us-east-1.elb.amazonaws.com
