name: R-CMD-check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages("devtools")'
          Rscript -e 'install.packages("Sage-Bionetworks/dccvalidator")'
          Rscript -e 'devtools::install_deps(dependencies = TRUE)'

      - name: Run tests
        run: |
          Rscript -e 'install.packages("testthat")'
          Rscript -e 'testthat::test_dir("tests/testthat/")'
        continue-on-error: true
        id: run-tests

      - name: Save test results
        if: failure()
        run: |
          echo "Tests failed" > test-results.log
        id: save-results

      - name: Post test results to PR
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const core = require('@actions/core');
            const github = require('@actions/github');
            const fs = require('fs');
            const { execSync } = require('child_process');
            
            const context = github.context;

            const failedTests = fs.readFileSync('test-results.log', 'utf8');
            const issueComment = github.context.payload.pull_request.number;

            if (failedTests) {
              const body = `## :x: Test failures detected in this PR\n\n\`\`\`\n${failedTests}\n\`\`\``;
              github.rest.issues.createComment({
                ...context.repo,
                issue_number: issueComment,
                body: body
              });
            }
