name: R-CMD-check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          install.packages('devtools')
          devtools::install_deps(dependencies = TRUE)

      - name: Run tests
        run: |
          install.packages('testthat')
          testthat::test_dir('tests/testthat/')
        continue-on-error: true
        id: run-tests

      - name: Post test results to PR
        if: failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const core = require('@actions/core');
            const github = require('@actions/github');
            const fs = require('fs');
            const { execSync } = require('child_process');
            
            const context = github.context;

            const failedTests = execSync('cat results.log').toString();
            const issueComment = github.context.payload.pull_request.number;

            if (failedTests) {
              const body = `## :x: Test failures detected in this PR\n\n\`\`\`\n${failedTests}\n\`\`\``;
              github.rest.issues.createComment({
                ...context.repo,
                issue_number: issueComment,
                body: body
              });
            }

      - name: Save test results
        if: failure()
        run: |
          cat results.log > test-results.log
        continue-on-error: true
        id: save-results

