# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
# deploy on pull request approval and merge

name: shiny-apps-deploy

on:
  push:
    branches:
      - master
      - prod
  workflow_dispatch:

jobs:
  shinyDeploy:
    runs-on: Ubuntu-20.04
    container: rocker/rstudio:4.1.3
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
 
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          # The rsconnect R package needs cUrl.  This app needs the Java JDK (runtime AND compiler).
          sudo apt-get install -y libcurl4-openssl-dev default-jdk openssl libssl-dev libv8-dev libxml2-dev libssh2-1-dev zlib1g-dev libpng-dev

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          r-version: 'renv'

      # install packages
      - name: Install rsconnect
        run: |
          install.packages("renv")
          renv::upgrade(version = "0.17.3")
          renv::install("rsconnect@0.8.29")
          renv::install("httr")
        shell: Rscript {0}

      # this action activates renv
      - uses: r-lib/actions/setup-renv@v2

      - name: Deploy app
        run: |
          renv::restore(packages = "renv")

          branch<-Sys.getenv("GITHUB_REF_NAME")
          repo<-Sys.getenv("GITHUB_REPOSITORY")
          appName<-strsplit(repo, "/")[[1]][2]
          if (!startsWith(branch, "prod")) {
             appName = paste(appName, "staging", sep="-")
          }
          rsConnectUser <-"${{ secrets.RSCONNECT_USER }}"
          rsConnectToken <- "${{ secrets.RSCONNECT_TOKEN }}"
          rsConnectSecret <- "${{ secrets.RSCONNECT_SECRET }}" 
          
          # create env file
          config <- "client_name=Stop AD Forms"
          config <- c(config, "client_id=${{ secrets.OAUTH_CLIENT_ID }}")
          config <- c(config, "client_secret=${{ secrets.OAUTH_CLIENT_SECRET }}")
          appUrl<- sprintf("https://%s.shinyapps.io/%s", rsConnectUser, appName)
          config <- c(config, sprintf("app_url=%s", appUrl))
         
          envFileConn<-file(".Renviron")
          tryCatch(
             writeLines(config, envFileConn),
             finally=close(envFileConn)
          )         
          
          # https://github.com/rstudio/rsconnect/issues/124
          options(rsconnect.max.bundle.files=100000)
          options(rsconnect.max.bundle.size=3145728000)
          rsconnect::setAccountInfo(rsConnectUser, rsConnectToken, rsConnectSecret)
          appFiles<-dir(all.files=TRUE, include.dirs=TRUE)
          rsconnect::deployApp(appName = appName, appFiles=appFiles, forceUpdate = TRUE)
        shell: Rscript {0}
