# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: shiny-apps-deploy

on:
  push:
    branches:
      - master
      - shinyapps-and-docker
      - release*

jobs:
  shiny-deploy:
    runs-on: ubuntu-latest
 
    steps:
 
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          # The rsconnect R package needs cUrl.  This app needs the Java JDK (runtime AND compiler).
          sudo apt-get install -y libcurl4-openssl-dev default-jdk
 
      - uses: actions/checkout@v2
        
      # We don't use renv, so we want to skip the "renv::activate()" command in .Rprofile
      - name: disable renv
        run: rm .Rprofile
       
      - name: Install R packages
        run: |
          Sys.setenv(GITHUB_PAT="${{ secrets.pat_for_shinyapps_action }}")
          source("install-pkgs.R")
        shell: sudo Rscript {0}
       
      - name: Deploy app
        run: |
          branch<-Sys.getenv("GITHUB_REF_NAME")
          repo<-Sys.getenv("GITHUB_REPOSITORY")
          appName<-strsplit(repo, "/")[[1]][2]
          if (!startsWith(branch, "release")) {
             appName = paste(appName, "staging", sep="-")
          }
          rsConnectUser <-"${{ secrets.RSCONNECT_USER }}"
          rsConnectToken <- "${{ secrets.RSCONNECT_TOKEN }}"
          rsConnectSecret <- "${{ secrets.RSCONNECT_SECRET }}" 
          
          # create env file
          config <- "client_name=Stop AD Forms"
          config <- c(config, "client_id=${{ secrets.OAUTH_CLIENT_ID }}")
          config <- c(config, "client_secret=${{ secrets.OAUTH_CLIENT_SECRET }}")
          appUrl<- sprintf("https://%s.shinyapps.io/%s", rsConnectUser, appName)
          config <- c(config, sprintf("app_url=%s", appUrl))
         
          envFileConn<-file(".Renviron")
          tryCatch(
             writeLines(config, envFileConn),
             finally=close(envFileConn)
          )         
          
          # https://github.com/rstudio/rsconnect/issues/124
          options(rsconnect.max.bundle.files=100000)
          options(rsconnect.max.bundle.size=3145728000)
          rsconnect::setAccountInfo(rsConnectUser, rsConnectToken, rsConnectSecret)

          appFiles<-dir(all.files=TRUE, include.dirs=TRUE)

          # previous we added the parameter 'python=py_path' to the following line
          rsconnect::deployApp(appName = appName, appFiles=appFiles)
          # important NOT to run this step as sudo, otherwise env var's will be missing
        shell: Rscript {0}
